title: Ministry of Communications and Information
url: https://mci.gov.sg
favicon: /images/Logos/mci_english_horizontal_col.jpg
colors:
  primary-color: "#a7002d"
  secondary-color: "#127852"
  media-colors:
    - title: media-color-one
      color: "#c40233"
    - title: media-color-two
      color: "#00573f"
    - title: media-color-three
      color: "#8b8588"
    - title: media-color-four
      color: "#c40233"
    - title: media-color-five
      color: "#4a4a4a"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1kqig029hwcxx.amplifyapp.com
prod: https://master.d1kqig029hwcxx.amplifyapp.com
shareicon: /images/Logos/mci_english_horizontal_col.jpg
is_government: true
facebook-pixel: ""
google_analytics: ""
google_analytics_ga4: G-R8EVQPP6X3
linkedin-insights: ""
resources_name: media-centre
