title: Ministry of Digital Development and Information
url: https://www.mddi.gov.sg
favicon: /images/MDDI Logos/M.png
colors:
  primary-color: "#00ab84"
  secondary-color: "#005dac"
  media-colors:
    - title: media-color-one
      color: "#853494"
    - title: media-color-two
      color: "#ef413d"
    - title: media-color-three
      color: "#005dac"
    - title: media-color-four
      color: "#00ab84"
    - title: media-color-five
      color: "#f1a725"
description: The Ministry of Digital Development and Information (MDDI) drives
  Singapore’s digital development in four key domains — the economy, government,
  security, and society. MDDI oversees the development of the infocomm
  technology, cybersecurity, and media sectors; the Government’s digitalisation
  initiatives; and the national library, national archives, and public
  libraries. The Ministry is also responsible for effective public
  communications, and the Government’s information and public communication
  policies. MDDI’s mission is to engage hearts and minds to achieve a thriving
  digital future for all.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d1smzutswyav9j.amplifyapp.com
prod: https://master.d3gycxy3tjxrco.amplifyapp.com
shareicon: /images/MDDI Logos/MDDI_LOGO_RGB_resize.png
is_government: true
facebook-pixel: ""
google_analytics: ""
google_analytics_ga4: G-5PP6LQ80HY
linkedin-insights: ""
resources_name: media-centre
